export interface Section { id: string; title: string; paragraphs: string[]; code?: string; diagram?: boolean }
export const docs: Record<string, {title: string; intro: string; sections: Section[]}> = {
 specifications: { title: 'Reading a specification', intro: 'An authored contract and a verified outcome are different kinds of information.', sections: [
  {id:'lifecycle',title:'Lifecycle is an owner decision',paragraphs:['Draft means proposed authority. Approved means the owner ratified the contract. Superseded and retired describe its place in the authority history. None of these labels proves the implementation works.']},
  {id:'implementation',title:'Implementation is a declaration',paragraphs:['Pending, in-progress, complete, deferred and n-a are source declarations. Complete does not automatically mean released, deployed or qualified. This catalog displays the source declaration without upgrading it into a stronger claim.']},
  {id:'ownership',title:'Territory and relationships',paragraphs:['Specifications declare claimed units and relationships to other specifications. Use the source repository and its supported spec-spine reads to assess authority. The website is a reading surface rather than a second governance judge.']},
  {id:'evidence',title:'Evidence has a scope',paragraphs:['A local test, a hosted CI run, a release artifact and a deployment exercise establish different facts. This metadata export does not join those evidence sets, so verification and deployment qualification remain visibly unknown.']},
 ]},
 catalog: { title: 'How the catalog is built', intro: 'Public sources, immutable revisions and a supported read interface.', sections: [
  {id:'pins',title:'A reviewed source snapshot',paragraphs:['The source manifest pins twelve public repositories to exact Git revisions, spec-spine 0.28.0 and an observation date of October 3, 2026. A routine build does not follow moving branches. Updating the snapshot is a reviewed source change.']},
  {id:'reads',title:'Supported producer reads',paragraphs:['The exporter verifies public visibility, checks each pinned corpus for freshness, and uses spec-spine config, registry list, show and relationships commands. It validates and deterministically sorts a website-owned presentation payload. It never parses managed registry shards directly.','Missing required sources, stale corpus data, unsupported producer requirements, schema errors or missing relationship targets fail the export. Prerendering fails without required catalog data and checks the complete route set.']},
  {id:'limits',title:'What is exported, and what is not',paragraphs:['The catalog contains declared lifecycle and implementation, summaries, ownership claims, relationships, source headings, frozen anchors, content hashes and pinned public markdown links. Released spec-spine 0.28.0 has no selected-content command. Full sections are available through the linked source, not reconstructed from derived files.','Verification and qualification are unknown in this export. Observation dates describe the snapshot rather than a claim of current branch state.']},
  {id:'privacy',title:'The publication boundary',paragraphs:['The public build has no access to the private platform corpus. Any future platform summary needs an owner-approved selected publication contract before the website may consume it. Local evidence, handoffs, secrets and private infrastructure material are excluded from the static artifact.','There are no analytics, third-party scripts or remote fonts. Theme preference is saved locally in your browser.']},
 ]},
};
export const paper = {
 title: 'Intent, authority, evidence', subtitle: 'A working model for governed software change', date: 'October 3, 2026',
 abstract: 'The useful unit of software governance is a bounded claim: what should change, who may change it, and which evidence supports the result. The public Statecraft family provides tools for those questions while keeping their answers separate.',
 sections: [
  {id:'intent',title:'01. Start with a contract',paragraphs:['A specification records intended behavior and its limits before implementation. In spec-spine, authored markdown and typed relationships provide the inputs to a compiled authority record. Ownership is declared over concrete units rather than inferred from a broad product description.','This distinction makes a proposal reviewable. A draft is still a proposal, and approval belongs to its owner. Tools can validate structure and consistency; a green check does not supply the owner decision.']},
  {id:'authority',title:'02. Make authority inspectable',paragraphs:['An authority graph can answer which specifications claim affected territory and how they relate. Coupling checks tie changes to that declared territory. The guarantee is bounded by what is declared and what the gate checks. It is not operating-system isolation or proof that parallel tasks share no external resources.','Each public repository remains its own specification authority. The website exports a reading payload through supported producer commands and links back to exact source revisions. It does not replace the source graph or judge implementation acceptance.'],diagram:true},
  {id:'work',title:'03. Keep local work explicit',paragraphs:['Statecraft CLI describes a local environment for governed work. Project registration, read-only qualification, arming and execution posture are separate acts. Keeping those acts distinct avoids treating visibility in a project list as permission to execute.','Rahi provides a Rust chassis for governed applications, and Aicortex describes persistent memory for AI clients built on that chassis. A public codebase or a declared implementation does not establish a hosted service. The catalog therefore preserves declarations without inventing deployment status.']},
  {id:'evidence',title:'04. Evidence supports a bounded conclusion',paragraphs:['Wire Witness treats captured provider traffic as evidence rather than authority. Rustev proposes decisions rather than granting them. The family also includes focused primitives for deterministic decisions, trust scoring, canonical serialization, artifact emission and independent verification.','An append-only hash-linked record can establish internal consistency. Optional signing capabilities require a specific deployment and trust decision before issuer identity can be claimed. A verifier result, an approved specification and a deployed qualification should remain distinct in every public explanation.']},
  {id:'reading',title:'05. Read the record with its limits',paragraphs:['The public catalog shows lifecycle, implementation, summary, relationships, claimed units, headings and frozen anchors with immutable source provenance. Verification and deployment qualification remain unknown in this metadata export. That is a visible limitation rather than a missing badge to infer.','The current released producer does not export selected full sections. Follow the pinned markdown link for the complete specification. Future richer content or private-platform summaries need their own supported producer and publication contracts.']},
 ] satisfies Section[],
};
