import { useEffect, useRef, useState } from 'react';
import { Links, Meta, NavLink, Outlet, Scripts, ScrollRestoration, Link, isRouteErrorResponse, useRouteError } from 'react-router';
import './app.css';
const navigation = [['/products', 'Products'], ['/registry', 'Catalog'], ['/docs', 'Docs'], ['/papers', 'Papers'], ['/get-started', 'Get started']];
const themeScript = `try{let t=localStorage.getItem('theme')||'system';document.documentElement.dataset.theme=t;document.documentElement.style.colorScheme=t==='system'?'light dark':t}catch{}`;
export function Layout({ children }: { children: React.ReactNode }) {
  return <html lang="en" suppressHydrationWarning><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta name="theme-color" content="#142d28"/><link rel="icon" href="/favicon.svg" type="image/svg+xml"/><Meta/><Links/><script dangerouslySetInnerHTML={{ __html: themeScript }}/></head><body>{children}<ScrollRestoration/><Scripts/></body></html>;
}
export default function App() {
  const [open, setOpen] = useState(false);
  const [theme, setTheme] = useState('system');
  const menu = useRef<HTMLButtonElement>(null);
  useEffect(() => { try { const value = localStorage.getItem('theme') || 'system'; setTheme(value); document.documentElement.dataset.theme = value; document.documentElement.style.colorScheme = value === 'system' ? 'light dark' : value; } catch {} }, []);
  useEffect(() => { const escape = (e: KeyboardEvent) => { if (e.key === 'Escape' && open) { setOpen(false); menu.current?.focus(); } }; window.addEventListener('keydown', escape); return () => window.removeEventListener('keydown', escape); }, [open]);
  function changeTheme(value: string) { setTheme(value); document.documentElement.dataset.theme = value; document.documentElement.style.colorScheme = value === 'system' ? 'light dark' : value; try { localStorage.setItem('theme', value); } catch {} }
  return <><a className="skip" href="#main">Skip to content</a><header className="site-header"><div className="shell header-inner"><Link className="brand" to="/" aria-label="Statecraft home"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M3 6h11v9H3zM18 6h11v9H18zM3 19h26v7H3z" fill="currentColor"/></svg>statecraft<span className="brand-dot">.</span></Link><button className="menu-toggle" ref={menu} aria-expanded={open} aria-controls="site-nav" onClick={() => setOpen(!open)}>Menu {open ? '−' : '+'}</button><nav id="site-nav" className={open ? 'navigation is-open' : 'navigation'} aria-label="Main navigation">{navigation.map(([to, label]) => <NavLink key={to} to={to} onClick={() => setOpen(false)}>{label}</NavLink>)}</nav><label className="theme-label"><span className="sr-only">Color theme</span><select aria-label="Color theme" value={theme} onChange={e => changeTheme(e.target.value)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label></div></header><main id="main" tabIndex={-1}><Outlet/></main><footer className="site-footer shell"><div><Link className="brand" to="/">statecraft<span className="brand-dot">.</span></Link><p>Intent, authority, evidence.</p></div><div><a href="https://github.com/statecrafting">GitHub organization ↗</a><Link to="/docs/catalog">Catalog provenance</Link><p>Public sources. Static pages. No analytics.</p></div></footer></>;
}
export function ErrorBoundary() { const error = useRouteError(); const missing = isRouteErrorResponse(error) && error.status === 404; return <section className="shell page"><p className="eyebrow">{missing ? '404 / Not found' : 'Unable to load this page'}</p><h1>{missing ? 'This page is not in the catalog.' : 'The page could not be loaded.'}</h1><p>No substitute specification is shown.</p><Link to="/registry">Browse the catalog</Link></section>; }
